name: build_create-branch-config

on:
  push:
    branches: [main]
    paths:
      - build_create-branch-config/**
      - '*.json'
      - '*.js'
      - .github/workflows/build_create-branch-config.yaml
  pull_request:
    branches: [main]
    paths:
      - hello-world/**
      - '*.json'
      - '*.js'
      - .github/workflows/build_create-branch-config.yaml

defaults:
  run:
    working-directory: build_create-branch-config

jobs:
  test:
    environment: build_create-branch-config
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          apiToken: ${{ secrets.apiToken }}
          ownerName: ${{ secrets.ownerName }}
          appName: ${{ secrets.appName }}
          branch: ${{ github.ref_name }}
          config: ${{ secrets.config }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn workspace @appcenter-api-actions/common install
      - run: yarn workspace @appcenter-api-actions/common run build
      - run: yarn workspace @appcenter-api-actions/common run package
#       - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn package

      - name: e2e-test
        uses: ./build_create-branch-config
        with:
          apiToken: ${{ secrets.apiToken }}
          ownerName: ${{ secrets.ownerName }}
          appName: ${{ secrets.appName }}
          branch: ${{ github.ref_name }}
          config: ${{ secrets.config }}

#  generate:
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          ref: ${{ github.head_ref }}
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#          cache: yarn
#      - run: yarn
#      - run: yarn format
#      - uses: int128/update-generated-files-action@v2
